modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="Apache-2.0"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/infernalexp/Infernal-Expansion/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="infernalexp" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory

# A display name for the mod
displayName="Infernal Expansion" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://discord.gg/UYGSn94" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="Infernal_Expansion_Logo.png" #optional

# A text field displayed in the mod UI
credits="See the description!" #optional

# A text field displayed in the mod UI
authors="nekomaster1000" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A community-driven Vanilla+ mod that expands the Nether beyond the Nether Update,
introducing new biomes, blocks, mobs, and more!

Director:
- Nekomaster1000

Coders:
- BaconKami
- Blackgear
- CaelTheQuail
- Dayton_10
- Flenarn
- HellionGames
- LudoCrypt
- Merxlc
- Orcinus
- SwanX1

Main Artists:
- Nekomaster1000
- Sheddmer/Mocha
- GLaDOS Edition
- BaconKami

Main Composers:
- LudoCrypt

Special Thanks:
- JonahFuses
- LiveVoxel
- TelepathicGrunt
'''

[[dependencies.infernalexp]]
modId="forge"
mandatory=true
versionRange="[32,)"
ordering="NONE"
side="BOTH"
[[dependencies.infernalexp]]
modId="minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side="BOTH"
